### ISSUE TITLE
MTLloader substring wrong position

### ISSUE THREAD

**Issue by Pathompongmc** [hjoykim/THREE#14]
if(key=="ka" || key=="kd" || key=="ks" || key=="ke")
 {
    ==> fix with this == >  value = (pos >= 0) ? line.Substring(pos-1) : "";
                        value = value.Substring(pos).Trim();
                        var ss = Regex.Split(value, delimiter_pattern);
                        info.Add(key, new float[] { float.Parse(ss[0]), float.Parse(ss[1]), float.Parse(ss[2]) });
 }

**Comment by hjoykim** [comment]
I adopted your code , 
thanks for this bug finding.
