### ISSUE TITLE
DLL library 

### ISSUE THREAD

**Issue by elkhalafy** [hjoykim/THREE#15]
May you build it as DLL library with DLL library for render control to use ut on winforms? 

Also I hope build it for .net 4.0 or 4.5

Thank you.

**Comment by hjoykim** [comment]
I think you can build .net4.0/4.5 with changing project runtime target.
and I don't know exactly what's mean building  DLL library for DLL.

There are 3 projects in this solution(*.sln)
THREE, THREEExample project are class library and resulted as DLL file.
Other winforms project could be refered to THREE.dll or THREEExample.dll

**Comment by elkhalafy** [comment]
Thank you, I will try

I meant for .net with DLL that used for winforms to render or viewing control.

Yes, I got it

Thank you again.

**Comment by hjoykim** [comment]
I've been thinking about developing glcontrol for .net, but as you know, glControl depends on OpenTK.GLControl, and this OpenTK.GLControl doesn't support .Net yet.

Let's consider another way.

Thank you for your interest.
