### ISSUE TITLE
Why Renderer not center screen ?

### ISSUE THREAD

**Issue by Pathompongmc** [hjoykim/THREE#19]
Why Renderer not center screen ?

**Comment by hjoykim** [comment]
hello,
please, check if camera.View.Enabled is true or no in your camera setting of source 
if camera.View.Enabled is true, the rendering screen will be offset by camera.View.OffsetX, OffsetY.
the default value of camera.View.Enabled is false like as below

public Camera()
        {
            this.IsCamera = true;
            this.type = "Camera";

            View = new View()
            {
                Enabled = false,
                FullWidth = 1,
                FullHeight = 1,
                OffsetX = 0,
                OffsetY = 0,
                Width = 1,
                Height = 1
            };
        }
