### ISSUE TITLE
RectAreaLights

### ISSUE THREAD

**Issue by michaelsakharov** [hjoykim/THREE#2]
Do the Rect Area Lights work in your port yet?
Also, this is a great project! It took me a while to find it but this is by far the best Threejs port to .net.

**Comment by michaelsakharov** [comment]
Cant get them to work so I guess they don't?

**Comment by michaelsakharov** [comment]
![image](https://user-images.githubusercontent.com/8621606/161433900-1b12a19e-94c0-45ae-b3ca-027102fb16bc.png)
Did a bit of work and managed to get them Semi working, so it looks like all the code was there just missing the RectAreaLightHelper which I just ported over, I'm not really sure if I ported it over correctly, as it appears to be the more complicated of the Light Helpers. and I don't really know Javascript all that well.

**Comment by michaelsakharov** [comment]
![image](https://user-images.githubusercontent.com/8621606/161434604-81a217ad-5c6f-45a1-9d1f-f3f86b806124.png)
Looks like the Phong material doesn't work with it, also not sure what this weird Pattern is.

**Comment by michaelsakharov** [comment]
![image](https://user-images.githubusercontent.com/8621606/161435157-f9e30716-2a5c-441b-ba60-882fd10eba73.png)
Really not sure what could cause this

**Comment by michaelsakharov** [comment]
Commenting out like 61 in the Lights_Physical_Pars_Fragment.glsl shader fixes it, so its something with Specularity

**Comment by michaelsakharov** [comment]
Implemented the LTC Textures that were missing, I'm guessing thats the problem.
Not sure if I did it wrong though:
![image](https://user-images.githubusercontent.com/8621606/161441168-9120ab52-c326-4465-967a-51200a4a58f6.png)

**Comment by michaelsakharov** [comment]
Im thinking its most likely the .png format im storing the LTC files in. Needs another format i think...

**Comment by michaelsakharov** [comment]
Hmm, I think I have hit a roadblock for me at least. Not sure how to get the LTC images in, While maintaining the correct pixel data, especially with Bitmaps, I don't know if they even can store floats.

**Comment by michaelsakharov** [comment]
![image](https://user-images.githubusercontent.com/8621606/161443762-b406c0b0-98e9-4fbc-9265-1ede13e2f806.png)
For now disabled the LTC stuff in the shader, this works well enough

**Comment by michaelsakharov** [comment]
RectAreaLights seem to cause a Memory Leak, its Generating Infinite Textures.
Might be related to the LTC's

**Comment by michaelsakharov** [comment]
And fixed it, gonna close this Issue, Their Implemented Enough, the lack of LTC stuff sucks but atleast they work

**Comment by hjoykim** [comment]
OK!, good

**Comment by michaelsakharov** [comment]
I didn't manage to fix the LTC, But the Memory leak was a mistake on my side it was constantly trying to load the LTC textures when it should have only done it once.

**Comment by hjoykim** [comment]
Hi,
I updated some sources related to RectAreaLight.
please refer to three THREEExample.Three.Lights.RectArealightExample.cs
