### ISSUE TITLE
Update to .NET 8

### ISSUE THREAD

**Issue by zolkovacs** [hjoykim/THREE#27]
Could you please update it to .NET 8?

**Comment by hjoykim** [comment]
This git repository consists of five projects.
Among them, the THREE project is a basic set of APIs that must be implemented in all NET applications, so the project type is NET Standard, and all other projects are set to NET 6.
If you want to configure the application with NET 8, you can change each project attribute from NET 6 to NET 8 as shown in the picture below, except for THREE project.
The THREE project must be of Net standard type.
