### ISSUE TITLE
3d object loaders are not working

### ISSUE THREAD

**Issue by zolkovacs** [hjoykim/THREE#28]
3d object loaders (MTLLoader, OBJLoader, STLLoader, X3DLoader) throw an exception "The input string was not in a correct format".

Solution: Instead of using
   float.Parse(value)
please use
  float.Parse(value, CultureInfo.InvariantCulture.NumberFormat)
in the mentioned object loader classes.

**Comment by hjoykim** [comment]
sorry for the late reply. I have modified and committed all of the functions you mentioned.
Thanks for the suggestion.
