### ISSUE TITLE
Nuget package

### ISSUE THREAD

**Issue by Rez2557** [hjoykim/THREE#32]
Hello, it seems that not too long ago, the nuget package for this project dissappeared from nuget.org. Are there any plans to bring it back?

**Comment by hjoykim** [comment]
hello
THREE has never been distributed as a nuget package.
But there might be someone who needs it.
We will distribute it as a Nuget package.

If you have any other questions, please contact us at any time.

thank you

![image](https://github.com/user-attachments/assets/73827cbf-ef0c-4ff7-9ad0-f438808da2f9)
