### ISSUE TITLE
안녕하세요 instanceMesh SetColorAt 이 잘안됩니다.

### ISSUE THREAD

**Issue by KimMinWoo97** [hjoykim/THREE#33]
setColorAt 으로 어떤색상을 지정하던 검은색으로 출력되는데 방법이 있을까요

**Comment by hjoykim** [comment]
안녕하세요?
소스원본상 InstancedMesh에 InstancedColor  구현 method가 누락된 것 같습니다.
혹시 소스를 공유해주실수 있나요?
관련 버그를 수정해보겠습니다.

**Comment by hjoykim** [comment]
안녕하세요. 
InstancedMesh의 SetColorAt method를 구현하였습니다.

Three.js Instance Raycast Example을 참조하여 관련 예제를 커밋했으니
참조해보시고, 기타 에러가 발생하면 다시 알려주세요

![image](https://github.com/user-attachments/assets/a368e73d-a418-46fa-bf0d-62b42e551ee4)

**Comment by KimMinWoo97** [comment]
감사합니다 잘 되네요 :D
