### ISSUE TITLE
No objects in scene

### ISSUE THREAD

**Issue by merco** [hjoykim/THREE#35]
Hi. I can't see my objects in scene. Only background color.

![immagine](https://github.com/user-attachments/assets/3dedb56a-257d-44df-b9c9-17aeb1e3df2b)

What is missing in this basic code ? (source attached) 

![immagine](https://github.com/user-attachments/assets/9f625931-90d6-4573-86e4-5f3f5d7476fd)

[WinFormsApp1.zip](https://github.com/user-attachments/files/17062929/WinFormsApp1.zip)

**Comment by hjoykim** [comment]
Thanks to your interest

Have you solved this problem?

I think _Camera position is must set. but you've commented this.
Also trackball control event must be implemented in ThreeJsManager.vb and must to map to GlControl's mouse event in Forms1.vb

If you have any question please let me know

**Comment by merco** [comment]
yes it was camera position.
