### ISSUE TITLE
raycaster.IntersectObjects e obj without uv

### ISSUE THREAD

**Issue by merco** [hjoykim/THREE#38]
I get raycaster.IntersectObjects

I don't have "uv" in my attributes

![immagine](https://github.com/user-attachments/assets/131d173f-4082-494a-bb32-069e835abe82)

**Comment by hjoykim** [comment]
I'm not sure what problem you are facing.
(As you know, uv is not an attribute automatically created when creating a BufferGeometry, so it must be created separately.)

If you attach a source showing the phenomenon, I will try to find out what the problem is in THREE Classes.

**Comment by merco** [comment]
after rotating with mouse...

https://github.com/user-attachments/assets/228ca3ab-0e49-4155-8cc2-028e8d092fa9

[1M.OBJ.zip](https://github.com/user-attachments/files/17263340/1M.OBJ.zip)

In "Load scene" button load the above file.

[WinFormsApp1.vbproj.zip](https://github.com/user-attachments/files/17263347/WinFormsApp1.vbproj.zip)

**Comment by hjoykim** [comment]
I'v been update Mesh.cs for fixing uv and uv2 check when raycasting

**Comment by hjoykim** [comment]
the bug fixed code line number in Mesh.cs are
270, 295, 334 like as below
![image](https://github.com/user-attachments/assets/7e07b5d3-d3cb-46c8-bebb-7d6c9da9288d)



have you checked and updated  from the newest code Mesh.cs in repository?
