### ISSUE TITLE
Render low quality

### ISSUE THREAD

**Issue by merco** [hjoykim/THREE#39]
What determines this better visualization? Normals?

![immagine](https://github.com/user-attachments/assets/4272408e-05cf-4d04-9a30-b68d64beea5e)

[O{15}.zip](https://github.com/user-attachments/files/17263119/O.15.zip)

![immagine](https://github.com/user-attachments/assets/d5901c63-45d7-435d-88dd-11040a05cf33)

[O{22}.zip](https://github.com/user-attachments/files/17263211/O.22.zip)

**Comment by hjoykim** [comment]
Hello,
use below ComputeNormalsGroup function after loading obj file

public void ComputeNormalsGroup(Group group)
{
    group.Traverse(o =>
    {
        if (o is Mesh)
        {
            var tempGeom = new Geometry();
            (o.Geometry as BufferGeometry).deleteAttribute("normal");
            tempGeom.FromBufferGeometry((BufferGeometry)o.Geometry);
            tempGeom.MergeVertices();
            tempGeom.ComputeVertexNormals();
            tempGeom.NormalsNeedUpdate = true;
            o.Geometry = tempGeom;
        }
    });
}
...

 OBJLoader loader = new OBJLoader();
 var rootObject  =loader.Load("../../../../assets/models/obj/O{22}.obj");
 ComputeNormalsGroup(rootObject);

you can refer to [https://discourse.threejs.org/t/how-to-smooth-an-obj-with-threejs/3950](https://discourse.threejs.org/t/how-to-smooth-an-obj-with-threejs/3950)

**Comment by merco** [comment]
ok.

Now I have this problem with raycast


![immagine](https://github.com/user-attachments/assets/7b0b30b0-c432-4e6a-80da-caf8668b8a5a)

**Comment by merco** [comment]
now the objects are really soft!!  maybe too much  :)

![immagine](https://github.com/user-attachments/assets/dcc727c3-fb6e-4d84-bb84-e1100b23ef1f)

**Comment by hjoykim** [comment]
you can convert to BufferGeometry like as below




             //o.Geometry = tempGeom;
             (o.Geometry as BufferGeometry).FromGeometry(tempGeom);
