### ISSUE TITLE
WPF airspace problem

### ISSUE THREAD

**Issue by jingweilim** [hjoykim/THREE#53]
Hi, I am having z index issues in the WPFDemo. I think this is due to using OpenTK.winforms controls in a wpf app. 
I tried using Microsoft.DwayneNeed, but I was unable to fix it.
Does anyone know how to fix it?

**Comment by hjoykim** [comment]
Can you show me the screen and source of what happens regarding the z-index error?

**Comment by jingweilim** [comment]
![airspaceIssue](https://github.com/user-attachments/assets/61967b6d-6af7-481e-85d2-693ca9214e8a)
Screenshot of z index overlapping with telerik navigation view

![winForm](https://github.com/user-attachments/assets/4b4d00a1-90d1-4009-8032-548cc31eb5c2)
I think the issue is with using winformhost in GLRenderWindow.xaml

**Comment by hjoykim** [comment]
Hello

Try GLWpfControl instead of Windows FormsHost.

**Comment by hjoykim** [comment]
as mentioned above
Using GLWpfControl
Attached is an example project.

Please let me know the results.
[GLWPFDemo.zip](https://github.com/user-attachments/files/17529779/GLWPFDemo.zip)

**Comment by jingweilim** [comment]
Hi hjoykim, thanks for the answer. I will let you know in a few days as I am oversea

**Comment by jingweilim** [comment]
Hi hjoykim, I tried using GLWpfControl and it works, Thanks!

Unfortunately there was some clipping problems with ImGUI.
![ImGUI](https://github.com/user-attachments/assets/e7156260-dc87-4697-bac9-a9284bddd3c5)

**Comment by hjoykim** [comment]
hello
I think it was caused by Orthographic projection in ImGuiManager.
please show me your ImGuiManager and its integration source?

**Comment by jingweilim** [comment]
Sorry I can't insert code from my laptop, will have to use pictures instead.
Not much changes from ImGuiManager, all reference to GLControl changed to GLWpfControl.
displaySize changed to use actual width and height
![ImGUI2](https://github.com/user-attachments/assets/214ab266-cc22-4ea4-b506-31cd44fe6405)
![ImGUI3](https://github.com/user-attachments/assets/050100a7-06d2-4e9b-ad47-9f63e301c940)

**Comment by hjoykim** [comment]
It's the same file, but it's very strange.
The results I ran are shown in the screen below.
![image](https://github.com/user-attachments/assets/c87ce9f3-d575-4ebd-bd17-0e47afecfccc)
In the attached project file,
Please check ImGuiManager.cs .
[GLWPFDemo241107.zip](https://github.com/user-attachments/files/17660052/GLWPFDemo241107.zip)

**Comment by jingweilim** [comment]
Odd, It appears to be clipped on my screen
![ImGUI4](https://github.com/user-attachments/assets/03bdab04-2be2-4865-8c05-d868bdf45ef6)

I found a hack by making the clipping window larger
![ImGUI5](https://github.com/user-attachments/assets/59a25e7c-e7da-46f1-bfc9-ce99cf546a3d)
