### ISSUE TITLE
06-ambient-occlusion example looks incorrect

### ISSUE THREAD

**Issue by iulianiuga** [hjoykim/THREE#55]
It looks like the example "06-ambient-occlusion" is break, as running it looks like this: 
![image](https://github.com/user-attachments/assets/fb60544d-a2eb-484a-a40c-c745f3a3b10f)

Trying to implement the SSAO pass -> approx. same result
![image](https://github.com/user-attachments/assets/96b179b5-211e-44a6-89ce-05d040788923)

**Comment by hjoykim** [comment]
Hello

As three.js was versioned up, there were a lot of changes in SSAOPass, but it didn't reflect this properly.
Based on r129, SSOPass and related sources were modified and committed.
![image](https://github.com/user-attachments/assets/b20cd224-fc0d-4095-a100-314dcc579af2)
