### ISSUE TITLE
Treejs glft problem

### ISSUE THREAD

**Issue by merco** [hjoykim/THREE#57]
hello I have a question that goes beyond the threejs porting.

In my file format (a zip with the individual mesh geometries inside and then a json for matrices and positioning)

I'm trying to save the individual geometries in glft.

I think that the gltf optimization changes the base coordinates of the vertices and therefore the subsequent positionings are all wrong. Here's what happens by loading only the instances, without rotations and positionings.

Those with gltf all appear "normalized" on the origin, while the other vertices maintain their original positions.

How can I reposition the vertices (manipulated I think by the gltf optimizer) in order to use the matrices saved in my file?

Geometry saved from "obj"... manteins the "vertex coordinates"

![immagine](https://github.com/user-attachments/assets/53af7b6a-39e6-408c-a254-6d4df8527a83)

Geometry optimized with gltf ... seems 0,0 based

![immagine](https://github.com/user-attachments/assets/0433ca10-bfc7-4a35-97b2-3c9131550069)

**Comment by merco** [comment]
This is my javascript and testmodel file

[Uploading input_test.zip…]()

**Comment by merco** [comment]
... it runs well only if I use the main "scene" node from the "loader.parse".
I was trying to use the internal mesh of the scene node....
I don't know if  it could worsen the performance...

**Comment by hjoykim** [comment]
hello

how did you make your gltf file?

**Comment by merco** [comment]
With gltfpack.
After some reading on the web, I found out that the problem is solved by using the "scene" created by GLTFLoader rather than the geometry/mesh data...

I'm wondering if it's possible to port gltfloader to c#.
I'm using these libraries


https://cdn.jsdelivr.net/npm/three/examples/js/loaders/GLTFLoader.js
https://cdn.jsdelivr.net/npm/three/examples/js/loaders/DRACOLoader.js
meshopt_decoder.js
[meshopt_decoder.zip](https://github.com/user-attachments/files/17878775/meshopt_decoder.zip)

**Comment by hjoykim** [comment]
I think you can save your obj files to gltf using Assimp.net

I've commited AssimpLoader.cs please refer to

**Comment by merco** [comment]
Hi. I Need to use stream, so I've added a 

```
public Group Load(Stream stm, string formatExtensionHint= null)
{
    AssimpContext importer = new AssimpContext();
    var scene = importer.ImportFileFromStream(stm, PostProcessSteps.GenerateSmoothNormals | PostProcessSteps.Triangulate, formatExtensionHint);

    //var scene = importer.ImportFile(path, PostProcessSteps.GenerateSmoothNormals | PostProcessSteps.Triangulate);
    this.FilePath = "";

    lineMaterialSet.Clear();
    pointMaterialSet.Clear();

    basicMaterial.Color = Color.Hex(0xffff00);

    foreach (Assimp.Mesh m in scene.Meshes)
    {
        if (m.PrimitiveType == PrimitiveType.Point)
            pointMaterialSet.Add(m.MaterialIndex);
        else if (m.PrimitiveType == PrimitiveType.Line)
            lineMaterialSet.Add(m.MaterialIndex);
    }

    CreateMaterial(scene, lineMaterialSet, pointMaterialSet);

    return ProcessNode(scene.RootNode, scene);
}
```


bet then I get this exceptin from assimp (it's a glb file)

**Assimp.AssimpException: 'Error importing file: No suitable reader found for the file format of file "$$$___magic___$$$.".'
with these stream of file**

[f1.zip](https://github.com/user-attachments/files/17900663/f1.zip)

Any ideas?

**Comment by merco** [comment]
I'm using https://gltf-viewer.donmccurdy.com/ => it's ok
https://glb.ee/ => it's ok
https://imagetostl.com/it/visualizza-glb-online#convert  => it's ok
https://sandbox.babylonjs.com/  => it's ok
https://www.3dpea.com/it/view-GLB-online => it's ok


it uses 
 KHR_mesh_quantization and EXT_meshopt_compression.
